### ISSUE TITLE
Assertion 'int_ptr % MEM_ALIGNMENT == 0' failed in mem_heap_compress_pointer

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/jerryscript#784] opened 2015-12-14 15:32 UTC
###### Jerry version:
    Checked revision: 2c3c952
    Build: debug.linux
###### OS: 
    Ubuntu 15.10, x86_64
###### Test case:
```javascript
RegExp.prototype.toString();
RegExp.prototype.compile(RegExp.prototype);
```

###### Backtrace:
```
ICE: Assertion 'int_ptr % MEM_ALIGNMENT == 0' failed at jerryscript/jerry-core/mem/mem-heap.cpp(mem_heap_compress_pointer):811.
Error: ERR_FAILED_INTERNAL_ASSERTION

Program received signal SIGABRT, Aborted.
0x00000000004afcc5 in syscall_2_asm () at jerryscript/jerry-libc/target/linux/jerry-asm.S:32
32    SYSCALL_2
(gdb) bt
# 0  0x00000000004afcc5 in syscall_2_asm () at jerryscript/jerry-libc/target/linux/jerry-asm.S:32
# 1  0x00000000004003c2 in syscall_2 (syscall_no=62, arg1=6182, arg2=6)
    at jerryscript/jerry-libc/target/linux/jerry-libc-target.c:96
# 2  0x0000000000400563 in abort () at jerryscript/jerry-libc/target/linux/jerry-libc-target.c:175
# 3  0x0000000000437141 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.cpp:67
# 4  0x0000000000437190 in jerry_assert_fail (assertion=0x4d5ddd "int_ptr % MEM_ALIGNMENT == 0", 
    file=0x4d5848 "jerryscript/jerry-core/mem/mem-heap.cpp", 
    function=0x4b1210 <_ZZ25mem_heap_compress_pointerPKvE8__func__.lto_priv.1149> "mem_heap_compress_pointer", line=811)
    at jerryscript/jerry-core/jrt/jrt-fatals.cpp:99
# 5  0x00000000004a6d7c in mem_heap_compress_pointer (pointer_p=0x8e79f9 <mem_heap+1721>)
    at jerryscript/jerry-core/mem/mem-heap.cpp:811
# 6  0x00000000004a7188 in mem_compress_pointer (pointer_p=0x8e79f9 <mem_heap+1721>)
    at jerryscript/jerry-core/mem/mem-allocator.cpp:91
# 7  0x000000000045d8b1 in ecma_set_property_list (object_p=0x8e7908 <mem_heap+1480>, property_list_p=0x8e79f9 <mem_heap+1721>)
    at jerryscript/jerry-core/ecma/base/ecma-helpers.cpp:381
# 8  0x000000000045dff8 in ecma_create_named_data_property (obj_p=0x8e7908 <mem_heap+1480>, name_p=0x8e7960 <mem_heap+1568>, is_writable=true, 
    is_enumerable=false, is_configurable=false) at jerryscript/jerry-core/ecma/base/ecma-helpers.cpp:541
# 9  0x0000000000457b41 in re_initialize_props (re_obj_p=0x8e7908 <mem_heap+1480>, source_p=0x8e7960 <mem_heap+1568>, flags=0 '\000')
    at jerryscript/jerry-core/ecma/operations/ecma-regexp-object.cpp:209
# 10 0x000000000041c6b1 in ecma_builtin_regexp_prototype_compile (this_arg=743, pattern_arg=743, flags_arg=4)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-regexp-prototype.cpp:143
# 11 0x000000000041c2d1 in ecma_builtin_regexp_prototype_dispatch_routine (builtin_routine_id=201, this_arg_value=743, 
    arguments_list=0x9266c0 <mem_heap+258944>, arguments_number=1)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-regexp-prototype.inc.h:90
# 12 0x000000000049c691 in ecma_builtin_dispatch_routine (builtin_object_id=ECMA_BUILTIN_ID_REGEXP_PROTOTYPE, builtin_routine_id=201, this_arg_value=743, 
    arguments_list=0x9266c0 <mem_heap+258944>, arguments_number=1)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.inc.h:163
# 13 0x000000000049bd7d in ecma_builtin_dispatch_call (obj_p=0x8e79c0 <mem_heap+1664>, this_arg_value=743, arg_collection_p=0x8e79d8 <mem_heap+1688>)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.cpp:555
# 14 0x000000000044a4bd in ecma_op_function_call (func_obj_p=0x8e79c0 <mem_heap+1664>, this_arg_value=743, arg_collection_p=0x8e79d8 <mem_heap+1688>)
    at jerryscript/jerry-core/ecma/operations/ecma-function-object.cpp:1049
# 15 0x00000000004346d1 in opfunc_call_n (instr=..., frame_ctx_p=0x7fffffffcd80) at jerryscript/jerry-core/vm/opcodes.cpp:808
# 16 0x00000000004a7f45 in vm_loop (frame_ctx_p=0x7fffffffcd80, run_scope_p=0x0) at jerryscript/jerry-core/vm/vm.cpp:545
# 17 0x00000000004a81da in vm_run_from_pos (header_p=0x8e7800 <mem_heap+1216>, start_pos=1, this_binding_value=523, lex_env_p=0x8e7760 <mem_heap+1056>, 
    is_strict=false, is_eval_code=false, arg_collection_p=0x0) at jerryscript/jerry-core/vm/vm.cpp:643
# 18 0x00000000004a7c3e in vm_run_global () at jerryscript/jerry-core/vm/vm.cpp:415
# 19 0x00000000004aaed9 in jerry_run () at jerryscript/jerry-core/jerry.cpp:1533
# 20 0x00000000004a96b1 in main (argc=3, argv=0x7fffffffd3a8) at jerryscript/main-linux.cpp:459

```

**Comment by LaszloLango** [comment] 2016-02-08 09:57
Duplicate of #783

**Closed by LaszloLango** 2016-02-08 09:58 UTC
Labels: bug
