### ISSUE TITLE
Assertion 'string_p->refs_and_container >= ECMA_STRING_REF_ONE' failed in ecma_copy_or_ref_ecma_string

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/jerryscript#1031] opened 2016-04-25 16:54 UTC
###### Jerry version:
    Checked revision: 0c7d3fb
    Build: debug.linux
###### OS: 
    Ubuntu 15.10, x86_64
###### Test case:
```javascript
new RegExp();
new (new Date())(RegExp.prototype.compile(RegExp.prototype));
```

###### Backtrace:
```
ICE: Assertion 'string_p->refs_and_container >= ECMA_STRING_REF_ONE' failed at jerryscript/jerry-core/ecma/base/ecma-helpers-string.c(ecma_copy_or_ref_ecma_string):451.
Error: ERR_FAILED_INTERNAL_ASSERTION

Program received signal SIGABRT, Aborted.
0x000000000048d693 in syscall_2 () at jerryscript/jerry-libc/target/posix/jerry-asm.S:60
60    SYSCALL_2
(gdb) bt
# 0  0x000000000048d693 in syscall_2 () at jerryscript/jerry-libc/target/posix/jerry-asm.S:60
# 1  0x00000000004003e5 in raise (sig=6) at jerryscript/jerry-libc/target/posix/jerry-libc-target.c:117
# 2  0x00000000004003b7 in abort () at jerryscript/jerry-libc/target/posix/jerry-libc-target.c:103
# 3  0x0000000000414f38 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION)
    at jerryscript/targets/default/jerry-port-default-fatal.c:54
# 4  0x000000000041ebe7 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:68
# 5  0x000000000041ec2e in jerry_assert_fail (assertion=0x4a3fb8 "string_p->refs_and_container >= ECMA_STRING_REF_ONE", 
    file=0x4a3d50 "jerryscript/jerry-core/ecma/base/ecma-helpers-string.c", 
    function=0x4946b0 <__func__.3587.lto_priv.423> "ecma_copy_or_ref_ecma_string", line=451)
    at jerryscript/jerry-core/jrt/jrt-fatals.c:95
# 6  0x000000000043a614 in ecma_copy_or_ref_ecma_string (string_p=0x8bb3f0 <mem_heap+880>)
    at jerryscript/jerry-core/ecma/base/ecma-helpers-string.c:451
# 7  0x000000000044c48d in ecma_copy_value (value=882) at jerryscript/jerry-core/ecma/base/ecma-helpers-value.c:416
# 8  0x000000000044c4ef in ecma_copy_value_if_not_object (value=882)
    at jerryscript/jerry-core/ecma/base/ecma-helpers-value.c:438
# 9  0x000000000044e4e2 in ecma_named_data_property_assign_value (obj_p=0x8bb150 <mem_heap+208>, prop_p=0x8bb3f9 <mem_heap+889>, value=882)
    at jerryscript/jerry-core/ecma/base/ecma-helpers.c:1144
# 10 0x000000000042b0c8 in re_initialize_props (re_obj_p=0x8bb150 <mem_heap+208>, source_p=0x8bb3f0 <mem_heap+880>, flags=0)
    at jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:150
# 11 0x000000000047cb91 in ecma_builtin_regexp_prototype_compile (this_arg=211, pattern_arg=211, flags_arg=8)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-regexp-prototype.c:149
# 12 0x000000000047c71e in ecma_builtin_regexp_prototype_dispatch_routine (builtin_routine_id=201, this_arg_value=211, arguments_list=0x7fffffffcb80, 
    arguments_number=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-regexp-prototype.inc.h:90
# 13 0x000000000047b87f in ecma_builtin_dispatch_routine (builtin_object_id=ECMA_BUILTIN_ID_REGEXP_PROTOTYPE, builtin_routine_id=201, this_arg_value=211, 
    arguments_list=0x7fffffffcb80, arguments_number=1)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.inc.h:163
# 14 0x000000000047b0c8 in ecma_builtin_dispatch_call (obj_p=0x8bb3c8 <mem_heap+840>, this_arg_value=211, arguments_list_p=0x7fffffffcb80, 
    arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:535
# 15 0x00000000004381fb in ecma_op_function_call (func_obj_p=0x8bb3c8 <mem_heap+840>, this_arg_value=211, arguments_list_p=0x7fffffffcb80, 
    arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:651
# 16 0x0000000000482b03 in opfunc_call.lto_priv.805 (frame_ctx_p=0x7fffffffcbf0) at jerryscript/jerry-core/vm/vm.c:379
# 17 0x0000000000481ba0 in vm_execute (frame_ctx_p=0x7fffffffcbf0, arg_p=0x0, arg_list_len=0)
    at jerryscript/jerry-core/vm/vm.c:2431
# 18 0x0000000000481c68 in vm_run_with_inline_stack (frame_ctx_p=0x7fffffffcbf0, arg_p=0x0, arg_list_len=1)
    at jerryscript/jerry-core/vm/vm.c:2467
# 19 0x0000000000481e50 in vm_run (bytecode_header_p=0x8bb250 <mem_heap+464>, this_binding_value=35, lex_env_p=0x8bb0b8 <mem_heap+56>, is_eval_code=false, 
    arg_list_p=0x0, arg_list_len=1) at jerryscript/jerry-core/vm/vm.c:2541
# 20 0x000000000048273c in vm_run_global (error_value_p=0x7fffffffccd8) at jerryscript/jerry-core/vm/vm.c:190
# 21 0x00000000004894b2 in jerry_run (error_value_p=0x7fffffffce70) at jerryscript/jerry-core/jerry.c:1755
# 22 0x0000000000487699 in main (argc=3, argv=0x7fffffffd368) at jerryscript/main-unix.c:511
```

**Comment by akosthekiss** [comment] 2016-08-29 17:05
On current master (8edab96), jerry throws TypeError for the test case, which seems to be the right answer. Closing the issue, as it is not reproducible anymore.

**Closed by akosthekiss** 2016-08-29 17:05 UTC
Labels: bug, ecma builtins
