### ISSUE TITLE
Jerry API for reporting memory stats.

### ISSUE THREAD

**Issue by ILyoan** [Samsung/jerryscript#637] opened 2015-09-21 01:48 UTC
JerryScript provides a feature for reporting memory usage but we can only check it after program finishes. 

How about adding a API `jerry_api_mem_stats()` for reporting memory stats so that we can see it in middle of program execution. This will helpful to check how memory usage is changing during execution.
I'm fine with either printing memory stats directly out to stdout or retrieving it.

**Comment by LaszloLango** [comment] 2016-02-11 13:48
Duplicate of #681

**Closed by LaszloLango** 2016-02-11 13:48 UTC
Labels: api
