### ISSUE TITLE
ICE: Assertion 'end <= ecma_string_get_length (appended_string_p)' failed at (ecma_builtin_string_prototype_object_replace_append_substr):776

### ISSUE THREAD

**Issue by egavrin** [Samsung/jerryscript#744] opened 2015-11-24 14:19 UTC
Version: 17a5dd27bbbadc036d83be0448f9edfa90800147

System:
```
Linux eg 4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Output:
```

ICE: Assertion 'end <= ecma_string_get_length (appended_string_p)' failed at /home/eg/dev/jr/jerry-core/ecma/builtin-objects/ecma-builtin-string-prototype.cpp(ecma_builtin_string_prototype_object_replace_append_substr):776.
Error: ERR_FAILED_INTERNAL_ASSERTION

```
Test case:

```js
 '஻BBCB@abXde^'.replace(/|/g,"$'஻BBBB@abXde^ce((/aq");
```

```js
 '஻BB8B@abXde^'.replace(/a/g,"$஻Bce((/a%");
```

**Comment by LaszloLango** [comment] 2016-02-08 09:48
Fails on current master (91a0514).

**Comment by LaszloLango** [comment] 2016-04-19 13:30
Minimized testcase: `''.replace(/|/g,"஻");`

**Comment by akosthekiss** [comment] 2016-08-29 17:34
The issue is still valid on current master (8edab96).

**Comment by LaszloLango** [comment] 2016-09-08 12:47
#1332 is landed

**Closed by LaszloLango** 2016-09-08 12:47 UTC
Labels: bug, ecma builtins
